#!/bin/bash -e

./.docker_run.sh "cd /workspace && \
      git config --global user.email yosuke.akatsuka@gmail.com && \
      git config --global user.name pankona && \
      bundle exec rake gen_deploy"


